version: "3"

services:
  db:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: foobar
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magepw
  php:
    build: ./.docker/hhvm
    volumes:
      - ./www/htdocs:/var/www/public
      - .docker/hhvm/server.ini:/etc/hhvm/server.ini
      - .docker/hhvm/php.ini:/etc/hhvm/php.ini
    links:
      - db:db
  nginx:
    image: nginx:1.13.6
    ports:
      - "80:80"
    volumes:
      - ./www/htdocs:/usr/share/nginx/html
      - ./.docker/nginx:/etc/nginx/conf.d
    links:
      - php:php
    # debug mode:
    command: [nginx-debug, '-g', 'daemon off;']
